let a = {
    "name": "",
    "avatar": "",
    "totalEpisodes": 1,
    "episodes": [],
    "duration": 0,
    "nameEnglish": "",
    "trailer": {
        "title": "",
        "link": "",
    },
    "description": "",
    "tags": [],
    "status": "",
    "quality": "",
    "subtitle": "",
    "category": "",
    "format": "",
    "country": "",
    "genre": [],
    "year": "",
    "director": "",
    "cast": [],
    "rating": 0,
    "views": 0,
    "hot": false,
}